spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/employee_db
    password: '41494899'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  boot:
    message: Hello, Employee Service Spring Cloud Bus Demo
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka/
server:
  port: '8081'
